version: 0.2

env:
  variables:
    AWS_REGION: "ap-southeast-1"
    CLUSTER_NAME: "eks-cluster-cms"
    ECR_REPO: "776567512500.dkr.ecr.ap-southeast-1.amazonaws.com/nginx-custom"

phases:
  pre_build:
    commands:
      - "echo PRE_BUILD"
      - "aws sts get-caller-identity"
      - "aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO"
      - "export IMAGE_TAG=$CODEBUILD_BUILD_NUMBER"
      - "echo IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - "echo BUILD"
      - "docker build -t nginx-custom:$IMAGE_TAG ."
      - "docker tag nginx-custom:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG"

  post_build:
    commands:
      - "echo POST_BUILD"
      - "docker push $ECR_REPO:$IMAGE_TAG"
      - "aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME"
      - "kubectl version --client"
      - "kubectl auth can-i get nodes"
      - "kubectl get nodes"
      - "kubectl set image deployment/nginx nginx=$ECR_REPO:$IMAGE_TAG"
