version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 776567512500.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t nginx-custom .
      - docker tag nginx-custom:latest 776567512500.dkr.ecr.ap-southeast-1.amazonaws.com/nginx-custom:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 776567512500.dkr.ecr.ap-southeast-1.amazonaws.com/nginx-custom:latest

