version: 0.2

env:
  variables:
    AWS_REGION: ap-southeast-1
    AWS_DEFAULT_REGION: ap-southeast-1
    CLUSTER_NAME: eks-cluster-cms
    ECR_REPO: 776567512500.dkr.ecr.ap-southeast-1.amazonaws.com/nginx-custom

phases:
  install:
    commands:
      - echo Installing kubectl 1.29...
      - curl -L -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.29.0/2023-11-14/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl

      - echo Verifying kubectl...
      - file /usr/local/bin/kubectl
      - kubectl version --client
      - aws --version

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - echo Image tag is $IMAGE_TAG

  build:
    commands:
      - echo Building Docker image...
      - docker build -t nginx-custom:$IMAGE_TAG .
      - docker tag nginx-custom:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO:$IMAGE_TAG

      - echo Updating kubeconfig for EKS...
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - echo Verifying EKS access...
      - aws sts get-caller-identity
      - kubectl get nodes
      - kubectl auth can-i update deployment/nginx

      - echo Updating Kubernetes Deployment...
      - kubectl set image deployment/nginx nginx=$ECR_REPO:$IMAGE_TAG
