version: 0.2

env:
  variables:
    AWS_REGION: ap-southeast-1
    CLUSTER_NAME: eks-cluster-cms
    ECR_REPO: 776567512500.dkr.ecr.ap-southeast-1.amazonaws.com/nginx-custom

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - export IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - echo Image tag: $IMAGE_TAG

  build:
    commands:
      - echo Building Docker image...
      - docker build -t nginx-custom:$IMAGE_TAG .
      - docker tag nginx-custom:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO:$IMAGE_TAG

      - echo Updating kubeconfig for EKS...
      - aws eks update-kubeconfig \
        --region $AWS_REGION \
        --name $CLUSTER_NAME \
        --role-arn arn:aws:iam::776567512500:role/codebuild-nginx-ecr-build-service-role

      - echo Verifying identity...
      - aws sts get-caller-identity

      - echo Verifying EKS access...
      - kubectl get nodes

      - echo Updating Kubernetes Deployment...
      - kubectl set image deployment/nginx nginx=$ECR_REPO:$IMAGE_TAG
